name: Debug Postman Env Vars

on:
  push:
    branches: [ main ]   # triggers on any push to main

jobs:
  print-postman-env:
    runs-on: ubuntu-latest
    env:
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      POSTMAN_WORKSPACE_ID: ${{ secrets.POSTMAN_WORKSPACE_ID }}
      POSTMAN_COLLECTION_ID_API: ${{ secrets.POSTMAN_COLLECTION_ID_API }}
      POSTMAN_COLLECTION_ID_TESTS: ${{ secrets.POSTMAN_COLLECTION_ID_TESTS }}
      POSTMAN_ENV_ID_LOCAL: ${{ secrets.POSTMAN_ENV_ID_LOCAL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print Postman environment variables
        run: |
          echo "🔹 Workspace ID: ${POSTMAN_WORKSPACE_ID}"
          echo "🔹 API Collection ID: ${POSTMAN_COLLECTION_ID_API}"
          echo "🔹 Tests Collection ID: ${POSTMAN_COLLECTION_ID_TESTS}"
          echo "🔹 Local Environment ID: ${POSTMAN_ENV_ID_LOCAL}"
          echo "🔹 API Key length: ${#POSTMAN_API_KEY} characters (masked for safety)"
