# .github/workflows/postman-sync.yml
name: "Postman - Publish collections & env on main"
on:
  push:
    branches: [ main ]

jobs:
  publish-to-postman:
    runs-on: ubuntu-latest
    env:
      # Secrets you already added
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      POSTMAN_WORKSPACE_ID: ${{ secrets.POSTMAN_WORKSPACE_ID }}
      POSTMAN_COLLECTION_ID_API: ${{ secrets.POSTMAN_COLLECTION_ID_API }}
      POSTMAN_COLLECTION_ID_TESTS: ${{ secrets.POSTMAN_COLLECTION_ID_TESTS }}
      POSTMAN_ENV_ID_LOCAL: ${{ secrets.POSTMAN_ENV_ID_LOCAL }}

      # Paths to your local artifacts (edit if needed)
      COLL_API_PATH: postman/collections/accounts.postman_collection.json
      COLL_TESTS_PATH: postman/collections/accounts-tests.postman_collection.json
      ENV_LOCAL_PATH: postman/environments/accounts-local.postman_environment.json

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # --- Collections ---
      - name: Update API collection
        shell: bash
        run: |
          set -euo pipefail
          jq '{collection: .}' "$COLL_API_PATH" > /tmp/collection_api.json
          curl -fSs -X PUT "https://api.getpostman.com/collections/${POSTMAN_COLLECTION_ID_API}" \
            -H "X-Api-Key: ${POSTMAN_API_KEY}" \
            -H "Content-Type: application/json" \
            --data @/tmp/collection_api.json | jq -r '.collection.info.name + " updated"'

      - name: Update Tests collection
        shell: bash
        run: |
          set -euo pipefail
          jq '{collection: .}' "$COLL_TESTS_PATH" > /tmp/collection_tests.json
          curl -fSs -X PUT "https://api.getpostman.com/collections/${POSTMAN_COLLECTION_ID_TESTS}" \
            -H "X-Api-Key: ${POSTMAN_API_KEY}" \
            -H "Content-Type: application/json" \
            --data @/tmp/collection_tests.json | jq -r '.collection.info.name + " updated"'

      # --- Environment ---
      - name: Update Local environment
        shell: bash
        run: |
          set -euo pipefail
          jq '{environment: .}' "$ENV_LOCAL_PATH" > /tmp/env_local.json
          curl -fSs -X PUT "https://api.getpostman.com/environments/${POSTMAN_ENV_ID_LOCAL}" \
            -H "X-Api-Key: ${POSTMAN_API_KEY}" \
            -H "Content-Type: application/json" \
            --data @/tmp/env_local.json | jq -r '.environment.name + " updated"'

      # --- (Optional) Verify workspace contents ---
      - name: List workspace collections (optional)
        run: |
          curl -fSs -X GET "https://api.getpostman.com/workspaces/${POSTMAN_WORKSPACE_ID}" \
            -H "X-Api-Key: ${POSTMAN_API_KEY}" | jq -r '.workspace.collections[]?.name' || true
